remote_theme: eliottvincent/bay
header:
  pages:
    - name: Home
      slug: /     # <-- index.md
    - name: About me  # <-- CV.md
    - name: Scientific CV # <-- Science.md
    - name: Trips made  # <-- Trips.md
    - name: Trips to make  # <-- Trips.md
    - name: Music # <-- Music.md
    - name: Others # <-- Others.md
footer:
  show_powered_by: false
  contact:
    - name: Email
      value: s.espinola@gmail.com
      link: mailto:s.espinola@gmail.com
  follow:
    - name: LinkedIn
      link: http://linkedin.com/in/sergio-martin-espinola/
    - name: GitHub
      link: http://github.com/sergioespinola
