remote_theme: eliottvincent/bay
header:
  pages:
    - name: Home
      slug: /     # <-- index.md
    - name: About me  # <-- CV.md
    - name: Scientific CV # <-- Science.md
    - name: Trips made  # <-- Trips.md
    - name: Trips to make  # <-- Trips.md
    - name: Music # <-- Music.md
    - name: Others # <-- Others.md
    - name: Contact

