remote_theme: eliottvincent/bay
header:
  pages:
    - name: Home
      slug: /     # <-- index.md
    - name: About me  # <-- about.md
    - name: Scientific CV # <-- cv.md
    - name: Trips made  # <-- tripsmade.md
    - name: Trips to make  # <-- tripsmake.md
    - name: Music # <-- music.md
    - name: Others # <-- others.md
    - name: Contact # <-- contact.md
